version: "3.3"

services:
  backend:
    container_name: photo_selector_nodejs_server
    restart: on-failure
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27018:27017"