const TYPES = {
  GET_PHOTO_ORDER_FOR_USER : "GET_PHOTO_ORDER_FOR_USER",
  GET_PHOTO_ORDER_BY_ID : "GET_PHOTO_ORDER_BY_ID",
  SAVE_PHOTO_ORDER : "SAVE_PHOTO_ORDER",
  UPDATE_PHOTO_ORDER : "UPDATE_PHOTO_ORDER",
  IS_PHOTO_ORDERS_AVAILABLE : "IS_PHOTO_ORDERS_AVAILABLE",
};

export default TYPES;