version: '3.7'

services:
  client:
    container_name: photo_selector_client_portal
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true