version: '3.7'

services:
  client:
    container_name: photo_selector_client_portal
    restart: on-failure
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    expose:
      - "3000"
    environment:
      - CHOKIDAR_USEPOLLING=true